#!/bin/withenv sh

set -euo pipefail


#======================================================================================================================
# If auto reload is disabled, do nothing (s6-pause waits forever without using resources)
#======================================================================================================================

if [ "${BF_PROXY_AUTO_RELOAD-}" != "1" ] ; then
    s6-pause
fi


#======================================================================================================================
# Watch configuration files and regenerate / reload Caddy configuration when they change
#======================================================================================================================

nu -c "use bf-proxy autoreload ; autoreload"
